### ISSUE TITLE
Add darkmode please

### ISSUE THREAD

**Issue by Bjolav** [pajbot/pajbot#810] opened 2020-03-15 00:50 UTC
My eyeballs are sore

**Comment by alazymeme** [comment] 2020-03-15 01:01
Try this, should help a lot: https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

**Comment by Bjolav** [comment] 2020-03-15 04:10
> Try this, should help a lot: https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

I have that one but I don't use it that much due to it not working well with some of the websites that I use

**Comment by alazymeme** [comment] 2020-03-15 07:26
> > Try this, should help a lot: https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh
> 
> I have that one but I don't use it that much due to it not working well with some of the websites that I use.
> It also feels integral nowadays as a web developer to include a dark mode imo

1. It might feel "integral", but the version of semantic ui being used here is several years old. I believe it's from like 2012 and would require an entire interface redesign in order to implement the latest version.
2. If it doesn't work with some websites that you use, then make it a toggle-on option. I believe you can set it that it only works on certain websites. Not working by default.
3. This issue is a duplicate of https://github.com/pajbot/pajbot/issues/653

**Comment by pajlada** [comment] 2020-03-15 08:41
Duplicate of #653 

Yeah, while this feature would be great, as @alazymeme so eloquently pointed out the code is old, using an old style framework. I have a hard time seeing this be done. Sorry!

**Closed by pajlada** 2020-03-15 08:41 UTC
