### ISSUE TITLE
messages sent rank not updating 

### ISSUE THREAD

**Issue by ponaire** [pajbot/pajbot#1028] opened 2020-09-25 05:19 UTC
on xqc's pajbot stats, everything works perfectly, including the updating of messages sent. however, for some reason the messages sent rank has stayed the same for a very long time. Before this, it took a whole month until it updated. I believe that it updated after  i logged in, but it could be a coincidence. its now been a full week, and my messages sent rank is still the same. Im positive that it should have changed.

is there anyway to fix this? is this just happening to me? thanks a lot.

the only other thread i saw talking about this issue was closed without a solution/answer listed.

**Comment by TroyDota** [comment] 2020-09-25 06:33
I think @pajlada disabled this on his bots.

**Comment by TroyDota** [comment] 2020-09-25 06:35
Please refer to #971

**Comment by RAnders00** [comment] 2020-09-25 07:08
Duplicate of #971

**Closed by RAnders00** 2020-09-25 07:08 UTC
