### ISSUE TITLE
League of Legends Module Ideas

### ISSUE THREAD

**Issue by kpelelis** [pajbot/pajbot#213] opened 2016-03-02 22:05 UTC
1) Show current game's data like masteries, runes 
2) Store data about champions stats Average Games played, KDA(Kill/Death/Assist Ratio), Average minions www.op.gg is pretty great for these kind of data representation.
3) Have a bot LoL account that will whisper the streamer when someone subscribes or donates. There is an app called LoLChat. I think their chat service is based on XMPP protocol

I will refresh the post once I get more ideas 4Head

**Comment by dextermb** [comment] 2016-03-02 22:26
The issue is that riot limits the amount of times you can send a request, which could be an issue depending on how often the stats will be updated and how many bots will have the feature activated.

I think the default limit is:
- 10 requests every 10 seconds
- 500 requests every 10 minutes

**Comment by KostasPelelis** [comment] 2016-03-02 22:33
I think with proper caching this problem could eliminated. An average League game lasts 30 minutes so 1,5k requests would be enough even for more specific data. For example if you want to keep track of the current champion played you can do a request every 1 minute and check if the value has changed.

**Comment by Nacht123** [comment] 2016-05-05 08:00
1. if you see it in chat, its not the same as if you see it on lolking, you would always use a different website to get it again.
2. not worth to store data about a league game without a betting system on league games (and a problem if the user has to many accounts)
3. not sure if it is worth it to get a league chat bot for subs or donations,
the streamer can just open a subscriber list or/and donation list in the browser.

**Comment by RAnders00** [comment] 2020-12-14 21:00
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.

**Closed by RAnders00** 2020-12-14 21:00 UTC
