### ISSUE TITLE
Streamer_login permissions

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#655] opened 2019-11-07 07:48 UTC
I feel like the bot should ask for more perms in order to make it function properly. Eg: channel:moderate, user:edit:broadcast (I believe this is for title/game adjustments) - this should make for an overall "easier setup" when first starting with pajbot (then your bot doesn't require the editor role)

**Comment by RAnders00** [comment] 2019-11-08 22:13
duplicate of #450

**Comment by alazymeme** [comment] 2019-11-08 22:13
beat me to it FeelsWeirdMan

**Closed by RAnders00** 2019-11-08 22:13 UTC
